---
- hosts: servidores
  sudo: yes
  tasks:
    - name: add key
      command: apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

    - name: add repo mongodb
      shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list creates=/etc/apt/sources.list.d/10gen.list

    - name: install mongodb
      apt: name=mongodb-org update_cache=yes state=latest

    - name: check service
      service: name=mongod state=restarted

    - name: install pip
      apt: name=python-pip update_cache=yes state=latest

    - name: install pymongo
      pip: name=pymongo state=present

    - name: Create a new database and user
      mongodb_user: database=test_telefonica name=telefonica password=12345 state=present
